//:::::::::::::::::::::: AUTOGENERATED PARSE :::::::::::::::::::::::::::::::
   Parse.initialize("QFDHAYIxgeNrofyDI6kABUANT5QLOU0czweGbM0E",
    "8kaBIPhgOtWV5S2NeUafnwdQhgBdBDWAncMaJmSk");
    
    var TestObject = Parse.Object.extend("TestObject");
    var testObject = new TestObject();
      testObject.save({foo: "bar"}, {
      success: function(object) {
        $(".success").show();
      },
      error: function(model, error) {
        $(".error").show();
      }
    });
// ::::::::::::::::::::::::::::::::::::::::

// var user = new Parse.User();
// user.set("username", "Jazastry");
// user.set("password", "falfalafa");
// user.set("email", "jazastry@example.com");

var Question = Parse.Object.extend("Question");
  var question = new Question();
    question.save({title: "bar"}, {
    success: function(object) {
      $(".success").show();
    },
    error: function(model, error) {
      $(".error").show();
    }
});

var question = new Question();
question.set("title", "To be or not to be ?");
question.set("user", "Jazastry");
question.save();

  
// other fields can be set just like with Parse.Object
// user.set("phone", "02/650-555-0000");
  
question.signUp(null, {
  success: function(user) {
    // Hooray! Let them use the app now.
  },
  error: function(user, error) {
    // Show the error message somewhere and let the user try again.
    alert("Error: " + error.code + " " + error.message);
  }
});